# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

concat <- function(vec, separator) {
    .Call('_content_clust_concat', PACKAGE = 'content.clust', vec, separator)
}

expression <- function(p) {
    .Call('_content_clust_expression', PACKAGE = 'content.clust', p)
}

small_in_big <- function(i, small_start, small_end, big_start, big_end) {
    .Call('_content_clust_small_in_big', PACKAGE = 'content.clust', i, small_start, small_end, big_start, big_end)
}

have_overlap <- function(i, start1, end1, start2, end2) {
    .Call('_content_clust_have_overlap', PACKAGE = 'content.clust', i, start1, end1, start2, end2)
}

substract_sorted <- function(a, i, b_starts, b_ends) {
    .Call('_content_clust_substract_sorted', PACKAGE = 'content.clust', a, i, b_starts, b_ends)
}

find_children <- function(content, parents) {
    .Call('_content_clust_find_children', PACKAGE = 'content.clust', content, parents)
}

get_cell_set <- function(i, p, cells, geneOrder, starts) {
    .Call('_content_clust_get_cell_set', PACKAGE = 'content.clust', i, p, cells, geneOrder, starts)
}

is_in <- function(x, a) {
    .Call('_content_clust_is_in', PACKAGE = 'content.clust', x, a)
}

get_sep_genes <- function(i, p, geneOrder, child_genes) {
    .Call('_content_clust_get_sep_genes', PACKAGE = 'content.clust', i, p, geneOrder, child_genes)
}

process_oriented_graph <- function(i, p, cells, geneNames, geneOrder, content, starts) {
    .Call('_content_clust_process_oriented_graph', PACKAGE = 'content.clust', i, p, cells, geneNames, geneOrder, content, starts)
}

#' @export
content_clust <- function(i, p, cells, geneNames, geneOrder) {
    .Call('_content_clust_content_clust', PACKAGE = 'content.clust', i, p, cells, geneNames, geneOrder)
}

