# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Expression <- function(p) {
    .Call('_content_clust_Expression', PACKAGE = 'content.clust', p)
}

OneInAnother <- function(i, start1, end1, start2, end2) {
    .Call('_content_clust_OneInAnother', PACKAGE = 'content.clust', i, start1, end1, start2, end2)
}

HasOverlap <- function(i, start1, end1, start2, end2) {
    .Call('_content_clust_HasOverlap', PACKAGE = 'content.clust', i, start1, end1, start2, end2)
}

SubstractSorted <- function(a, p, b_start, b_end) {
    .Call('_content_clust_SubstractSorted', PACKAGE = 'content.clust', a, p, b_start, b_end)
}

#' @export
content_clust <- function(i, p, cells, geneNames, geneOrder) {
    .Call('_content_clust_content_clust', PACKAGE = 'content.clust', i, p, cells, geneNames, geneOrder)
}

#' @export
c_hello_world <- function() {
    invisible(.Call('_content_clust_c_hello_world', PACKAGE = 'content.clust'))
}

