# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

expression <- function(p) {
    .Call('_content_clust_expression', PACKAGE = 'content.clust', p)
}

small_in_big <- function(i, small_start, small_end, big_start, big_end) {
    .Call('_content_clust_small_in_big', PACKAGE = 'content.clust', i, small_start, small_end, big_start, big_end)
}

have_overlap <- function(i, start1, end1, start2, end2) {
    .Call('_content_clust_have_overlap', PACKAGE = 'content.clust', i, start1, end1, start2, end2)
}

substract_sorted <- function(a, i, b_start, b_end) {
    .Call('_content_clust_substract_sorted', PACKAGE = 'content.clust', a, i, b_start, b_end)
}

find_children <- function(content, parent) {
    .Call('_content_clust_find_children', PACKAGE = 'content.clust', content, parent)
}

get_cell_set <- function(i, p, cells, geneOrder, start) {
    .Call('_content_clust_get_cell_set', PACKAGE = 'content.clust', i, p, cells, geneOrder, start)
}

#' @export
content_clust <- function(i, p, cells, geneNames, geneOrder) {
    .Call('_content_clust_content_clust', PACKAGE = 'content.clust', i, p, cells, geneNames, geneOrder)
}

#' @export
c_hello_world <- function() {
    invisible(.Call('_content_clust_c_hello_world', PACKAGE = 'content.clust'))
}

